# This is a basic workflow to help you get started with Actions

name: Multi Jobs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Run Job 2
        run: echo Job2!
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Run Job 3
        run: echo Job3!
